### PR TITLE
Make sure systemd is reloaded after adding a Unit file

### PR DESCRIPTION
**Pull request by olive42**

### CODE REVIEW

**Comment by jmauro** [comment]
Are you sure this not done by chef itself?

**Comment by olive42** [comment]
No, this is not automatic yet.

See https://github.com/chef-cookbooks/chef-client/issues/428

**Comment by olive42** [comment]
Abandoned in favour of a better solution.

**Comment by endlessracingz** [comment]
> 

So what's the better solution? I am unable to find one. Please help me.

**Pull request closed without merging**
